# Generated by Django 5.1 on 2024-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0003_remove_aboutdetail_icon_remove_aboutme_arrow_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdetail',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='about_icons/'),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='arrow_image',
            field=models.ImageField(blank=True, null=True, upload_to='about_icons/'),
        ),
    ]
