# Generated by Django 5.1 on 2024-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0004_aboutdetail_icon_aboutme_arrow_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='skills/icons/')),
            ],
        ),
    ]
