# Generated by Django 5.1 on 2024-12-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0010_alter_skill_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutdetail',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
    ]
