# Generated by Django 5.1 on 2024-12-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
