# Generated by Django 5.1 on 2024-12-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0014_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='github_url',
        ),
    ]
