# Generated by Django 5.1 on 2024-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.URLField(blank=True, max_length=15, null=True),
        ),
    ]
