# Generated by Django 5.1 on 2024-12-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicweb', '0017_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
